### ISSUE TITLE
White Label

### ISSUE THREAD

**Issue by lyoshimi** [stone-pagamentos/api-stone#1]
Alterar "White label Stone" para "API da Stone" em todo o texto

**Comment by netojoaobatista** [comment]
@lyoshimi, isso não causará confusão?

Sempre que um desenvolvedor estiver fazendo uma integração e disser que está integrando com a API da Stone, será necessário perguntar para ele qual API. Se é a integração com a API da Stone adquirente ou se é com a API da Stone Gateway.

**Comment by lyoshimi** [comment]
Foi o que pediram aqui. Toda documentação estará dividida em nosso Dev Center e será devidamente indicada aos nossos integradores.
Acredito que não dê problema

**Comment by netojoaobatista** [comment]
Documentação atualizada com o novo nome
